### ISSUE TITLE
strange L.DomEvent.skipped & L.DomEvent.fakeStop "is not a function" errors

### ISSUE THREAD

**Issue by EricG-Personal** [w8r/Leaflet.Path.Drag#55]
I have a code pen at https://codepen.io/ericg97477/pen/eYMJrqj demonstrating the issue.

If I drag the square polygon, I get two errors in the console...

```
L.Path.Drag.js:6 Uncaught TypeError: L.DomEvent.fakeStop is not a function
    at i._onDragEnd (L.Path.Drag.js:6:3571)
    at HTMLDocument.o (DomEvent.js:108:13)
L.Path.Drag.js:6 Uncaught TypeError: L.DomEvent.skipped is not a function
    at i.<anonymous> (L.Path.Drag.js:6:3370)
```

I am not sure if this is a bug or something I am doing wrong. 

I do note that at https://leafletjs.com/reference.html#domevent, it does not mention `fakeStop` or `skipped` methods.

Perhaps these were in older releases of leaflet...?

**Comment by w8r** [comment]
I cannot get the e2e tests working on gh actions, but I have no bandwidth to resolve it either. so I can release just as it is

**Comment by EricG-Personal** [comment]
Cool. Thank you. If I experience any issues, I will let you know.

**Comment by EricG-Personal** [comment]
On my codpen, I changed JS Setting for your package to `https://unpkg.com/leaflet-path-drag`, which should get me the latest version. I believe it is grabbing 1.8-beta.3

However, I am now getting an error...

```
leaflet-path-drag:1 Uncaught ReferenceError: require is not defined
    at leaflet-path-drag:1:1
```

**Comment by karolis-k** [comment]
I updated to 1.8.0-beta.3, but I still get 
```ERROR TypeError: L.DomEvent.skipped is not a function
    at NewClass.<anonymous> (Path.Drag.js:213:20)
    at timer (zone.js:3083:47)
```
